### ISSUE TITLE
Problems sending the gamestate to clients

### ISSUE THREAD

**Issue by TheZoq2** [HannesTuhkala/plen#6]
We get a trailing character error again. plz fix @Emiluren

**Comment by TheZoq2** [comment]
see the `sending_gamestate` branch

**Comment by TheZoq2** [comment]
kthxbye

**Comment by TheZoq2** [comment]
Oh just det, god morgon

**Comment by Emiluren** [comment]
Fixed by [this commit](https://github.com/HannesTuhkala/flying-broccoli/commit/ce68a758f76b12834a29ea9a61086b5c64b00303)
